# Generated by Django 3.1.6 on 2021-02-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dynamin_img')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
